# Generated by Django 2.1.7 on 2019-08-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_auto_20190615_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
